### ISSUE TITLE
allow cluster creation with default configuration

### ISSUE THREAD

**Issue by prashantknagarro** [angelabad/terraform-aws-msk-cluster#7]
The modules create new configuration even if you don't set server.properties. There is no option to create msk with default configuration. A property can be added to module to skip configuration creation.

**Comment by angelabad** [comment]
This configuration creates empty server.properties, so is the default cluster config. This is as is because if you create a cluster with msk configuration and after that you want to remove it, terraform apply fails. So the unique option is always hace a msk configuration, even if it is empty.

Thanks for your comment!
